# WRITE FUNCTIONS
## Checks if a command exists
function exists() {
  # `command -v` is similar to the `which` command
  # https://stackoverflow.com/a/677212
  command -v $1 >/dev/null 2>&1

  # More explicitly written:
  # command -v $1 1>/dev/null 2>/dev/null
}

. "$HOME/.cargo/env"
