# SET VARIABLES
## Bypass MacOS Gatekeeper for Homebrew Cask Installs
export HOMEBREW_CASK_OPTS="--no-quarantine"
## Set null to use bat instead of cat
export NULLCMD=bat

# CHANGE ZSH OPTIONS

# CREATE ALIASES
## Coloured output for ls and git status using exa
alias ls="exa -laFh --git"
alias exa="exa -laFh --git"
## Syntax highlighting for man (manual) pages using bat-extras
alias man=batman
## Syntax highlighting for grep (search) using bat-extras
alias grep=batgrep
## Shows the path variable, split by newline, in bat (default: cat)
alias trail='<<<${(F)path}'
## Remove to system trash
alias rm=trash

# CUSTOMISE PROMPT(S)
## Enable substitution in the prompt.
setopt prompt_subst
## Autoload zsh add-zsh-hook and vcs_info functions (-U autoload w/o substition, -z use zsh style)
autoload -Uz add-zsh-hook vcs_info
## Run vcs_info just before a prompt is displayed (precmd)
add-zsh-hook precmd vcs_info
## Enable checking for (un)staged changes, enabling use of %u and %c
zstyle ':vcs_info:*' check-for-changes true
## Set the format of the Git information for vcs_info
zstyle ":vcs_info:git:*" formats " %F{white}%f %F{cyan}%b%u%c%f"
zstyle ":vcs_info:git:*" actionformats " %F{white}%f %F{cyan}%b|%a%u%c%f"
## Set custom strings for an unstaged vcs repo changes (*) and staged change (+)
zstyle ':vcs_info:*' unstagedstr ' %F{red}✱%f'
zstyle ':vcs_info:*' stagedstr ' %F{green}✚%f'

precmd() {
  vcs_info
  print ""
  NEWLINE="
"
  if [[ -n ${vcs_info_msg_0_} ]]; then
    # vcs_info found nothing so we have more space. Let's print a longer part of $PWD...
    CUSTOM_PROMPT="%K{black} %F{green}%B%n%b%f %k%K{black}%F{white}%f %F{yellow}%B$(echo $PWD | perl -pe "s/(\w)[^\/]+\//\1\//g")%b%f%B${vcs_info_msg_0_}%b%k%K{black} %k%F{black}%f${NEWLINE}%(?.%F{green}.%F{red})❱%f "
    
  else
    # vcs_info found something that needs space, a shorter $PWD makes sense.
    CUSTOM_PROMPT="%K{black} %F{green}%B%n%b%f %k%K{black}%F{white}%f %F{yellow}%B%~%b%f %k%F{black}%f${NEWLINE}%(?.%F{green}.%F{red})❱%f "
  fi
}

prompt () {
  PS1=${CUSTOM_PROMPT}
}

rprompt () {
  RPROMPT="%F{black}%f%K{black} %B%(?.%F{green}✔.%F{red}✘)%f%b %F{white}%f %F{white}%*%f %F{white}%f %F{magenta}%B%L%b%f %k"
}

precmd_functions+=(
  prompt
  rprompt
)

# ADD LOCATIONS TO $path Array VARIABLE
typeset -U path
path=(
  $path
  "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
)

## pyenv
### TODO: This currently seems irrelevant as it does not add anything to $PATH.
# local pyenv_path="$HOME/.pyenv"
# export PYENV_ROOT="$HOME/.pyenv"
# command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"

# WRITE FUNCTIONS
function mkcd() {
  mkdir -p "$@" && cd "$_"
}

function cdls() {
  cd "$@" && command exa
}

# USE ZSH PLUGINS
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.dotfiles/dotfiles/config/zsh/plugins/nvm.zsh

# ...AND OTHER SUPRISES
## Some useful options (man zshoptions)
zle_highlight=('paste:none')

## Basic auto/tab complete:
ZSH_DISABLE_COMPFIX=true
autoload -Uz compinit && compinit
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'm:{a-zA-Z}={A-Za-z} l:|=* r:|=*'
zmodload zsh/complist
_comp_options+=(globdots)