# SET VARIABLES
## Bypass MacOS Gatekeeper for Homebrew Cask Installs
export HOMEBREW_CASK_OPTS="--no-quarantine"
export NULLCMD=bat
export NVM_PREFIX="/opt/homebrew/opt/nvm"

# CHANGE ZSH OPTIONS

# CREATE ALIASES
## Coloured output for ls and git status using exa
alias ls="exa -laFh --git"
alias exa="exa -laFh --git"
## Syntax highlighting for man (manual) pages using bat-extras
alias man=batman
## Syntax highlighting for grep (search) using bat-extras
alias grep=batgrep
## Shows the path variable, split by newline, in bat (default: cat)
alias trail='<<<${(F)path}'
## Remove to system trash
alias rm=trash

# CUSTOMISE PROMPT(S)
precmd() { print "" }
PROMPT="%B%F{green}%n%f%b at %F{cyan}%m%f in %B%F{yellow}%~%f%b
> "
RPROMPT="%* | %B%F{red}%L%f%b"

# ADD LOCATIONS TO $PATH VARIABLE
## Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

## nvm
local NVM_PREFIX="/opt/homebrew/opt/nvm"
export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_PREFIX/nvm.sh" ] && \. "$NVM_PREFIX/nvm.sh"  # This loads nvm
  [ -s "$NVM_PREFIX/etc/bash_completion.d/nvm" ] && \. "$NVM_PREFIX/etc/bash_completion.d/nvm"

# WRITE FUNCTIONS
## Make a directory, and cd into it
function mkcd() {
  mkdir -p "$@" && cd "$_"
}

# USE ZSH PLUGINS

# ...AND OTHER SUPRISES