#!/usr/bin/env zsh

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "<<< STARTING BREW BUNDLE >>>\n"
brew bundle dump --force --describe --file=./homebrew/brewfile && echo "Homebrew dumped a bundle in $BASEDIR/homebrew/brewfile.\n" || echo "Homebrew failed to dump a bundle.\n"
