["shaders"]
    type = "archive"
    url = "https://github.com/sahaj-b/cursor-shaders/archive/0a274beac8b93ee6ce6b94402b7313a0417b8e38.tar.gz"
    checksum.sha256 = "ffc19d75806eda04ccadec684e32bdf1b5849bafbb28bbea84cfea101ef86ff2"
    exact = true
    stripComponents = 1
