tap "azure/functions"
tap "go-swagger/go-swagger"

brew "ansible"
brew "cmake"
brew "delve"
brew "dust"
brew "gh"
brew "llvm"
brew "shellcheck"
brew "taplo"
brew "tree-sitter-cli"
brew "uv"
brew "worktrunk"
brew "azure/functions/azure-functions-core-tools@4"
brew "go-swagger/go-swagger/go-swagger"

cask "claude-code"
cask "docker-desktop"
cask "harper-desktop"
cask "postman"
cask "visual-studio-code"

vscode "ms-playwright.playwright"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.remote-explorer"
vscode "varlock.env-spec-language"
