tap "azure/functions"
tap "eth-p/software"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "romkatv/powerlevel10k"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Open source suite of directory software
brew "openldap"
# Modern replacement for 'ls'
brew "exa"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# General-purpose data compression with high compression ratio
brew "xz"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Mac App Store command-line interface
brew "mas"
# Manage multiple Node.js versions
brew "nvm"
# General-purpose scripting language
brew "php"
# Python version management
brew "pyenv"
# Utility that provides fast incremental file transfer
brew "rsync"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Azure Functions Core Tools 2.0
brew "azure/functions/azure-functions-core-tools"
# Bash scripts that integrate bat with various command-line tools
brew "eth-p/software/bat-extras"
# Application launcher and productivity software
cask "alfred"
# Git client focusing on productivity
cask "gitkraken"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Interface for reading and syncing eBooks
cask "kindle"
# Cable-free audio router
cask "loopback"
# Web browser
cask "microsoft-edge"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Visual communication software
cask "omnigraffle"
# Project planning and management software
cask "omniplan"
# Collaboration platform for API development
cask "postman"
# Command-line shell and scripting language
cask "powershell"
# Screen recorder with audio
cask "screenflick"
# Text editor for code, markup and prose
cask "sublime-text"
# To-do list
cask "todoist"
# Open-source code editor
cask "visual-studio-code"
# Video communication and virtual meeting platform
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "BetterSnapTool", id: 417375580
mas "Compressor", id: 424390742
mas "Disk Speed Test", id: 425264550
mas "Final Cut Pro", id: 424389933
mas "Ground News", id: 1324203419
mas "Microsoft To Do", id: 1274495053
mas "Motion", id: 434290957
mas "OverPicture", id: 1188020834
mas "The Unarchiver", id: 425424353
mas "Userscripts", id: 1463298887
mas "Xcode", id: 497799835
