[settings]
idiomatic_version_file_enable_tools = ["node"]
not_found_auto_install = false
go_set_gopath = true

[tools]
go = "1.25"
"go:github.com/wailsapp/wails/v2/cmd/wails" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
node = "lts"
pnpm = "latest"
python = "latest"
rust = "latest"
vercel = "latest"
