name: validate

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  render:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install chezmoi
        run: |
          mkdir -p "$RUNNER_TEMP/bin"
          sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$RUNNER_TEMP/bin"
          echo "$RUNNER_TEMP/bin" >> "$GITHUB_PATH"
      - name: Validate
        run: ./scripts/validate
